# custom
cfg:
  db-host: ${DB_HOST:127.0.0.1}
  db-port: ${DB_PORT:3306}
  db-user: ${DB_USER:root}
  db-pwd: ${DB_PWD:123456}

minio:
  endpoint: http://127.0.0.1:8080
  access_key: minio_admin
  secret_key: minio_admin
  app_bucket: test

# configuration
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${cfg.db-host}:${cfg.db-port}/test
    username: ${cfg.db-user}
    password: ${cfg.db-pwd}

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl