# custom
cfg:
  db-host: 127.0.0.1
  db-port: 3306
  db-user: root
  db-pwd: 123456

minio:
  endpoint: http://127.0.0.1:8080
  access_key: minio_admin
  secret_key: minio_admin
  app_bucket: test

# configuration
server:
  port: 8080

spring:
  profiles:
    active: local-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${cfg.db-host}:${cfg.db-port}/test
    username: ${cfg.db-user}
    password: ${cfg.db-pwd}
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
